services:
  - type: web
    name: ease-invoice
    env: php
    region: oregon
    plan: free
    buildCommand: |
      # Install Composer if not available
      if ! command -v composer &> /dev/null; then
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        rm composer-setup.php
      fi
      
      # Install PHP dependencies
      composer install --no-dev --optimize-autoloader --no-interaction
      
      # Set proper permissions
      chmod -R 755 .
      
    startCommand: php -S 0.0.0.0:$PORT -t .
    
    envVars:
      - key: PHP_VERSION
        value: "8.2"
      - key: DATABASE_URL
        fromDatabase:
          name: ease-invoice-db
          property: connectionString
      - key: APP_ENV
        value: production

databases:
  - name: ease-invoice-db
    databaseName: ease_invoice
    user: ease_invoice_user